mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sports/', include('sports.urls')),
]

sports/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login,logout


app_name = 'sports'
urlpatterns = [
    # 运动会代表队报名界面
    path('group/register/', views.group_register, name = "group_register"),
    
    path('group/get_athlete_div/', views.get_athlete_div, name = "group_get_athlete_div"),

    path('group/register/submit/', views.group_register_submit, name = "group_register_submit"),

    # 数据库设置项目
    path('insert_default_table/', views.insert_default_table, name = "insert_default_table"),
    
    # 安排比赛轮次
    path('arrange_match/', views.arrange_match, name = "arrange_match"),

    # 裁判打分界面
    path('judge/score/', views.judge_score, name = "judge_score"),

    path('judge/score/get_group_num/', views.judge_get_group_num, name = "judge_get_group_num"),

    path('judge/score/get_form/', views.judge_get_form, name = "judge_get_form"),

    path('judge/score/update_score/', views.judge_update_score, name = "judge_update_score"),
    
    # 总裁判提交总分界面
    path('alljudge/score/', views.alljudge_score, name = "alljudge_score"),

    path('alljudge/score/get_group_num/', views.alljudge_get_group_num, name="alljudge_get_group_num"),

    path('alljudge/score/get_form/', views.alljudge_get_form, name="alljudge_get_form"),
    
    path('alljudge/score/update_score/', views.alljudge_update_score, name="alljudge_update_score"),

    path('insert_default_table/', views.insert_default_table, name = "insert_default_table"),
    
    # 登陆界面

    path('login/',views.login,name = "group_login"),
    
    path('pre_login/',views.pre_login, name="pre_login"),
    
    # 注册界面

    path('register/',views.team_register),
    
    path('pre_register/',views.pre_team_register),

    # 运动会总成绩展示界面

    path('score_board/person/',views.score_board, name='score_board'),

    path('score_board/person/get_form/', views.board_person_get_form, name="board_person_get_form"),
    
    path('pre_register',views.pre_team_register,name="pre_register"),
    
    path('pre_judge_register',views.pre_judge_register),
    
    path('judge_register',views.judge_register),
    
    path('pre_judge_login',views.pre_judge_login, name='pre_judge_login'),
    
    path('judge_login',views.judge_login),

    path('score_board/team/',views.score_board_team, name='score_board_team'),

    path('score_board/team/get_form/', views.board_team_get_form, name="board_team_get_form"),
]

sports/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.template.loader import render_to_string
from django.db import models
from .models import Team, TeamLeader, TeamInstructor, Athlete, TeamDoctor, Project, Participate, AgeGroup,Team_User
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.contrib.auth.views import login,logout
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import auth

from .models import Team, TeamLeader, TeamInstructor, Athlete, TeamDoctor
from .models import Project, Participate, AgeGroup, Judge, Score, FinalScore
import random

# Create your views here.

def group_index(request):
    return render(request, "sports/group-index.html", locals())    

def group_register(request):
    
    teamname = request.session['teamname']
    
    print(request.session['teamname'])
    return render(request, "sports/group-register.html", locals())    

def get_athlete_div(request):
    number = request.POST["number"]
    number = int(number) - 1
    html = render_to_string('sports/athlete-div.html', {'number': number})
    return HttpResponse(html)

def group_register_submit(request):
    
    team = Team.objects.filter(Team_name = request.session['teamname'] )[0]
    # team = Team.objects.create(Team_account_number = '01',
    #                            Team_account_password = '00',Team_name = request.session['teamname'])
    #team = Team.objects.filter(pk = 1)
    
    # print("----"+team)
    captain_name = request.POST["captain_name"]
    captain_id = request.POST['captain_id']
    captain_phone = request.POST['captain_phone']
    
    doctor_name = request.POST["doctor_name"]
    doctor_id = request.POST['doctor_id']
    doctor_phone = request.POST['doctor_phone']
    
    coach_name = request.POST["coach_name"]
    coach_id = request.POST['coach_id']
    coach_phone = request.POST['coach_phone']
    coach_sex = request.POST['coach_sex']

    athlete_num = int(request.POST["athlete_num"])
    
    for i in range(athlete_num):
        athlete_names = request.POST.getlist("athlete_name")
        athlete_name = athlete_names[i]
        athlete_ids = request.POST.getlist("athlete_id")
        athlete_id = athlete_ids[i]
        athlete_sexs = request.POST.getlist("athlete_sex")
        athlete_sex = athlete_sexs[i]
        
        athlete_age_groups = request.POST.getlist("athlete_age")
        print(athlete_age_groups)
        athlete_age_group_id = athlete_age_groups[i]
        print(athlete_age_group_id)
        print(AgeGroup.objects.filter(age_name=athlete_age_group_id))
        athlete_age_group = AgeGroup.objects.get(age_name = athlete_age_group_id)

        athlete_projectsss = request.POST.getlist("athlete_project")
        athlete_projectss = athlete_projectsss[i]
        athlete_projects = athlete_projectss.split(',')

        # athlete = Athlete(athlete_team=team, athlete_name=athlete_name, athlete_id_cardnumber=athlete_id,
        #                   athlete_sex=athlete_sex,
        #                   athlete_age=athlete_age_group)
        athlete = Athlete.objects.create(athlete_team=team, athlete_name=athlete_name, athlete_id_cardnumber=athlete_id,
                          athlete_sex=athlete_sex,
                          athlete_age=athlete_age_group)
        # athlete = Athlete(athlete_team = team[0], athlete_name = athlete_name, athlete_id_cardnumber = athlete_id, athlete_sex = athlete_sex,
        # athlete_age = athlete_age_group)
        athlete.save()

        for project_name in athlete_projects:

            project = Project.objects.get(Project_name = project_name, Project_agegroup = athlete_age_group, Project_sex = athlete_sex)
            participate = Participate(athlete = athlete, project = project)
            participate.save()

    captain = TeamLeader.objects.create(TeamLeader_team=team, TeamLeader_name=captain_name,
                         TeamLeader_Phonenumber=captain_phone, TeamLeader_id_cardnumber=captain_id)
    captain.save()

    # captain = TeamLeader(TeamLeader_team = team[0], TeamLeader_name = captain_name,
    # TeamLeader_Phonenumber = captain_phone, TeamLeader_id_cardnumber = captain_id)
    # captain.save()
    #

    doctor = TeamDoctor.objects.create(TeamDoctor_team=team, TeamDoctor_name=doctor_name,
                        TeamDoctor_id_cardnumber=doctor_id, TeamDoctor_Phonenumber=doctor_phone)
    doctor.save()
    # doctor = TeamDoctor(TeamDoctor_team = team[0], TeamDoctor_name = doctor_name,
    # TeamDoctor_id_cardnumber = doctor_id,TeamDoctor_Phonenumber = doctor_phone)
    # doctor.save()


    coach = TeamInstructor.objects.create(TeamInstructor_team=team, TeamInstructor_name=coach_name,
                           TeamInstructor_id_cardnumber=coach_id, TeamInstructor_sex=coach_sex,
                           TeamInstructor_Phonenumberv=coach_phone)
    coach.save()
    # coach = TeamInstructor(TeamInstructor_team = team[0], TeamInstructor_name=coach_name,
    # TeamInstructor_id_cardnumber=coach_id, TeamInstructor_sex = coach_sex, TeamInstructor_Phonenumberv = coach_phone)
    # coach.save()

    return HttpResponse("ok")

def insert_default_table(request):
    sex_id = 1
    age_group_dict = {1:'1',2:'2',3:'3'}
    
    for age_group_id in range(1, 4):
        for project_id in range(1, 8):
            ageGroup = AgeGroup.objects.get(age_name = str(age_group_id))   
            project = Project(Project_name = str(project_id), Project_agegroup = ageGroup, Project_sex = str(sex_id))
            project.save()
    
    a = [4, 8, 9, 5, 7]
    sex_id = 2
    for age_group_id in range(1, 4):
        for a_id in range(5):
            project_id = a[a_id]
            ageGroup = AgeGroup.objects.get(age_name = str(age_group_id))   
            project = Project(Project_name = str(project_id), Project_agegroup = ageGroup, Project_sex = str(sex_id))
            project.save()
    return HttpResponse("ok")

def arrange_match(request):
    for project in Project.objects.all():
        athletes = Participate.objects.filter(project = project)
        num = len(athletes)
        list = [i for i in range(0, num)]
        random.shuffle(list)
        for i, athlete in enumerate(athletes):
            athlete.group_number = list[i] / 6 + 1
            athlete.serial_number = list[i] % 6 + 1
            athlete.save()
    return HttpResponse("ok")

def judge_score(request):
    judge_name = request.session['judgename']
    return render(request, "sports/judge-score.html", locals())    

def judge_get_group_num(request):
    sex = request.POST["sex"]
    age = request.POST["age"]
    print(age)
    print(AgeGroup.objects.all())
    age_group = AgeGroup.objects.get(age_name = age)
    project_id = request.POST["project"]

    project = Project.objects.get(Project_name = project_id, Project_agegroup = age_group, Project_sex = sex)
    athletes = Participate.objects.filter(project = project)

    num = len(athletes)
    num = (int(num) - 1) // 6 + 1
    return HttpResponse(num)

def judge_get_form(request):
    sex = request.POST["sex"]
    age = request.POST["age"]
    age_group = AgeGroup.objects.get(age_name = age)
    project_id = request.POST["project"]
    project = Project.objects.get(Project_name = project_id, Project_agegroup = age_group, Project_sex = sex)
    group = request.POST['group']
    athletes = Participate.objects.filter(project = project, group_number = group).order_by("serial_number")
    
    data = {}
    data['number'] = len(athletes)
    data['athlete'] = []
    for athlete in athletes:
        athlete = athlete.athlete
        athlete_info = {}
        athlete_info["name"] = athlete.athlete_name;
        athlete_info["team"] = athlete.athlete_team.Team_name;
        data['athlete'].append(athlete_info)
        
    return JsonResponse(data)


def alljudge_score(request):
    return render(request, "sports/all-judge-score.html", locals())


def alljudge_get_group_num(request):
    sex = request.POST["sex"]
    age = request.POST["age"]
    age_group = AgeGroup.objects.get(age_name=age)
    project_id = request.POST["project"]

    project = Project.objects.get(Project_name=project_id, Project_agegroup=age_group, Project_sex=sex)
    athletes = Participate.objects.filter(project=project)
    num = len(athletes)
    num = (int(num) - 1) // 6 + 1
    return HttpResponse(num)

def pre_login(request):
    return render(request, "sports/login.html")
    



def login(request):
    username = request.POST.get('username',False)
    password = request.POST.get('password',False)
    print(request.POST)
    # username = request.POST['username']
    # password = request.POST['password']
    print(username)
    print(password)
    user = authenticate(username = username,password = password)
    if user is not None and user.is_active:
        auth.login(request,user)
        team_user = Team_User.objects.get(user = user)
        team_name = team_user.teamname
        request.session['teamname'] = team_name
        print("right")
        print(request.session['teamname'])
        return HttpResponse(1)
    else:
        return HttpResponse(2)
    
    
def pre_team_register(request):
    return render(request,"sports/register.html",locals())


def team_register(request):
    username = request.POST.get("username",False)
    password = request.POST.get("password",False)
    teamname = request.POST.get("teamname",False)
    

    team = Team.objects.create(Team_account_number = Team_User.pk,
                               Team_account_password = password,Team_name = teamname)
    team.save()
    # username = request.POST["username"]
    # password = request.POST["password"]
    # teamname = request.POST["teamname"]
    print(username)
    print(password)
    print(teamname)

sports/templates/sports/board-base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en-us">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" /> {% comment %}
  <link rel="icon" href="favicon.ico" /> {% endcomment %}
  <!--jquery库-->
  <script src="{% static 'sports/js/jquery.min.js' %}"></script>
  <!--bootstrap库-->
  <link href="{% static 'sports/css/bootstrap.min.css' %}" rel="stylesheet" />
  <script src="{% static 'sports/js/bootstrap/bootstrap.min.js' %}"></script>
  <!--[if lt IE 9]>
      <script src="js/bootstrap/html5shiv.min.js"></script>
      <script src="js/bootstrap/respond.min.js"></script>
    <![endif]-->
  <!--font-awesome字体库-->
  <link href="{% static 'sports/css/font-awesome.min.css' %}" rel="stylesheet" />
  <!--页面加载进度条-->
  <link href="{% static 'sports/css/pace/dataurl.css' %}" rel="stylesheet" />
  <script src="{% static 'sports/js/pace/pace.min.js' %}"></script>
  <!--jquery.hammer手势插件-->
  <script src="{% static 'sports/js/jquery.hammer/hammer.min.js' %}"></script>
  <script src="{% static 'sports/js/jquery.hammer/jquery.hammer.js' %}"></script>
  <!--平滑滚动到顶部库-->
  <script src="{% static 'sports/js/jquery.scrolltopcontrol/scrolltopcontrol.js' %}" type="text/javascript"></script>
  <!--主要写的jquery拓展方法-->
  <script src="{% static 'sports/js/jquery.extend.js' %}" type="text/javascript"></script>
  <!--主要写的css代码-->
  <link href="{% static 'sports/css/default.css' %}" rel="stylesheet" type="text/css" />
  <!--主要写的js代码-->
  <script src="{% static 'sports/js/default.js' %}" type="text/javascript"></script>
  <link href="{% static 'sports/css/base.css' %}" rel="stylesheet" type="text/css" />
  <!-- sweetalert插件 -->
  <script src="{% static 'sports/js/sweet-alert.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'sports/css/sweet-alert.css' %}"> {% block css %} {% endblock %}
  <title>运动会总成绩</title>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle show pull-left" data-target="sidebar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
          aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'sports:score_board' %}">运动会总成绩</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <!-- <li>
            <a href="{% url 'sports:score_board' %}">个人成绩</a>
          </li>
          <li>
            <a href="{% url 'sports:score_board_team' %}">团队成绩</a>
          </li> -->
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid all">
    <div class="sidebar">
      <ul class="nav">
        <li>
          <a href="{% url 'sports:score_board' %}">个人成绩</a>
        </li>   
        <li>
          <a href="{% url 'sports:score_board_team' %}">团队成绩</a>
        </li>      
      </ul>
    </div>
    <div class="maincontent row">
      <!--我是主要内容 start-->
      {% block content %} {% endblock %}
      <!--我是主要内容 end-->
    </div>
  </div>
  <a href="#top" id="goTop">
    <i class="fa fa-angle-up fa-3x"></i>
  </a>
  <script>
    $.ajaxSetup({
      headers: {
        "X-CSRFToken": '{{ csrf_token }}'
      }
    });
  </script>
  {% block js %} {% endblock js %}</body>

</html>

sports/templates/sports/group-base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en-us">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" /> {% comment %}
  <link rel="icon" href="favicon.ico" /> {% endcomment %}
  <!--jquery库-->
  <script src="{% static 'sports/js/jquery.min.js' %}"></script>
  <!--bootstrap库-->
  <link href="{% static 'sports/css/bootstrap.min.css' %}" rel="stylesheet" />
  <script src="{% static 'sports/js/bootstrap/bootstrap.min.js' %}"></script>
  <!--[if lt IE 9]>
      <script src="js/bootstrap/html5shiv.min.js"></script>
      <script src="js/bootstrap/respond.min.js"></script>
    <![endif]-->
  <!--font-awesome字体库-->
  <link href="{% static 'sports/css/font-awesome.min.css' %}" rel="stylesheet" />
  <!--页面加载进度条-->
  <link href="{% static 'sports/css/pace/dataurl.css' %}" rel="stylesheet" />
  <script src="{% static 'sports/js/pace/pace.min.js' %}"></script>
  <!--jquery.hammer手势插件-->
  <script src="{% static 'sports/js/jquery.hammer/hammer.min.js' %}"></script>
  <script src="{% static 'sports/js/jquery.hammer/jquery.hammer.js' %}"></script>
  <!--平滑滚动到顶部库-->
  <script src="{% static 'sports/js/jquery.scrolltopcontrol/scrolltopcontrol.js' %}" type="text/javascript"></script>
  <!--主要写的jquery拓展方法-->
  <script src="{% static 'sports/js/jquery.extend.js' %}" type="text/javascript"></script>
  <!--主要写的css代码-->
  <link href="{% static 'sports/css/default.css' %}" rel="stylesheet" type="text/css" />
  <!--主要写的js代码-->
  <script src="{% static 'sports/js/default.js' %}" type="text/javascript"></script>
  <link href="{% static 'sports/css/base.css' %}" rel="stylesheet" type="text/css" />
  <!-- sweetalert插件 -->
  <script src="{% static 'sports/js/sweet-alert.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'sports/css/sweet-alert.css' %}"> {% block css %} {% endblock %}
  <title>运动会代表队管理</title>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle show pull-left" data-target="sidebar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
          aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'sports:group_register' %}">运动会代表队</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          {% comment %}
          <li>
            <a href="top1.html">top1.html</a>
          </li>
          <li>
            <a href="top2.html">top2.html</a>
          </li>
          <li>
            <a href="top3.html">top3.html</a>
          </li>
          <li>
            <a href="https://github.com/shihao316558512/bootstrap" target="_blank">
              <i class="fa fa-download fa-fw"></i>&nbsp;原码下载</a>
          </li> {% endcomment %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <i class="fa fa-user fa-fw"></i>&nbsp;{{ teamname }}&nbsp;
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              {% comment %}
              <li>
                <a href="top-right1.html">top-right1.html</a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="top-right2.html">top-right2.html</a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="top-right3.html">
                  <i class="fa fa-sign-out fa-fw"></i>&nbsp;top-right3.html</a>
              </li> {% endcomment %}
              <li>
                <a href="{% url 'sports:pre_login' %}">退出登陆</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid all">
    <div class="sidebar">
      <ul class="nav">
        <li>
          <a href="{% url 'sports:group_register' %}">报名运动会</a>
        </li>

      </ul>
    </div>
    <div class="maincontent row">
      <!--我是主要内容 start-->
      {% block content %} {% endblock %}
      <!--我是主要内容 end-->
    </div>
  </div>
  <a href="#top" id="goTop">
    <i class="fa fa-angle-up fa-3x"></i>
  </a>
  <script>
    $.ajaxSetup({
      headers: {
        "X-CSRFToken": '{{ csrf_token }}'
      }
    });
  </script>
  {% block js %} {% endblock js %}</body>

</html>

sports/templates/sports/judge-base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en-us">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" /> {% comment %}
  <link rel="icon" href="favicon.ico" /> {% endcomment %}
  <!--jquery库-->
  <script src="{% static 'sports/js/jquery.min.js' %}"></script>
  <!--bootstrap库-->
  <link href="{% static 'sports/css/bootstrap.min.css' %}" rel="stylesheet" />
  <script src="{% static 'sports/js/bootstrap/bootstrap.min.js' %}"></script>
  <!--[if lt IE 9]>
      <script src="js/bootstrap/html5shiv.min.js"></script>
      <script src="js/bootstrap/respond.min.js"></script>
    <![endif]-->
  <!--font-awesome字体库-->
  <link href="{% static 'sports/css/font-awesome.min.css' %}" rel="stylesheet" />
  <!--页面加载进度条-->
  <link href="{% static 'sports/css/pace/dataurl.css' %}" rel="stylesheet" />
  <script src="{% static 'sports/js/pace/pace.min.js' %}"></script>
  <!--jquery.hammer手势插件-->
  <script src="{% static 'sports/js/jquery.hammer/hammer.min.js' %}"></script>
  <script src="{% static 'sports/js/jquery.hammer/jquery.hammer.js' %}"></script>
  <!--平滑滚动到顶部库-->
  <script src="{% static 'sports/js/jquery.scrolltopcontrol/scrolltopcontrol.js' %}" type="text/javascript"></script>
  <!--主要写的jquery拓展方法-->
  <script src="{% static 'sports/js/jquery.extend.js' %}" type="text/javascript"></script>
  <!--主要写的css代码-->
  <link href="{% static 'sports/css/default.css' %}" rel="stylesheet" type="text/css" />
  <!--主要写的js代码-->
  <script src="{% static 'sports/js/default.js' %}" type="text/javascript"></script>
  <link href="{% static 'sports/css/base.css' %}" rel="stylesheet" type="text/css" />
  <!-- sweetalert插件 -->
  <script src="{% static 'sports/js/sweet-alert.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'sports/css/sweet-alert.css' %}"> {% block css %} {% endblock %}
  <title>裁判打分管理</title>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle show pull-left" data-target="sidebar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false"
          aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'sports:judge_score' %}">运动会裁判</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          {% comment %}
          <li>
            <a href="top1.html">top1.html</a>
          </li>
          <li>
            <a href="top2.html">top2.html</a>
          </li>
          <li>
            <a href="top3.html">top3.html</a>
          </li>
          <li>
            <a href="https://github.com/shihao316558512/bootstrap" target="_blank">
              <i class="fa fa-download fa-fw"></i>&nbsp;原码下载</a>
          </li> {% endcomment %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <i class="fa fa-user fa-fw"></i>&nbsp;{{judge_name}}&nbsp;
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              {% comment %}
              <li>
                <a href="top-right1.html">top-right1.html</a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="top-right2.html">top-right2.html</a>
              </li>
              <li class="divider"></li>
              <li>
                <a href="top-right3.html">
                  <i class="fa fa-sign-out fa-fw"></i>&nbsp;top-right3.html</a>
              </li> {% endcomment %}
              <li>
                <a href="{% url 'sports:pre_judge_login' %}">退出登陆</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid all">
    <div class="sidebar">
      <ul class="nav">
        <li>
          <a href="{% url 'sports:judge_score' %}">运动员打分</a>
        </li>
      </ul>
    </div>
    <div class="maincontent row">
      <!--我是主要内容 start-->
      {% block content %} {% endblock %}
      <!--我是主要内容 end-->
    </div>
  </div>
  <a href="#top" id="goTop">
    <i class="fa fa-angle-up fa-3x"></i>
  </a>
  <script>
    $.ajaxSetup({
      headers: {
        "X-CSRFToken": '{{ csrf_token }}'
      }
    });
  </script>
  {% block js %} {% endblock js %}</body>

</html>